# Training parameters
training:
  batch_size: 100
  learning_rate: 0.01
  weight_decay: 0.001
  num_epochs: 100
  episodes_per_epoch: 10
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1

# Model parameters
model:
  window_size: 65  # 13 weeks
  hidden_dim: 64
  use_spatial_attention: true
  use_gcn: true
  use_adaptive_adj: true
  num_assets_select: 4
  relation_file: "relation_matrix.npy"

# Backtest parameters
backtest:
  initial_balance: 10000
  transaction_fee: 0.001
  holding_period: 25  # 5 weeks

# Environment parameters
environment:
  initial_balance: 10000
  transaction_fee: 0.001
  reward_type: "return"  # Options: "sharpe", "sortino", "max_drawdown", "return" 